version: '2'

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${SERVER_PORT:-3000}:${SERVER_PORT:-3000}
    security_opt:
      - seccomp:unconfined
    environment:
      - PUBSWEET_SECRET=${PUBSWEET_SECRET}
      - SERVER_PORT=${SERVER_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - PUBLIC_URL=${PUBLIC_URL}
      - NODE_ENV=production
